export const parcelStatus = {
  REQUESTED: "REQUESTED",
  ASSIGNED: "ASSIGNED",
  PICKED: "PICKED",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  RETURNED: "RETURNED",
};
